apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend      
    spec:
      containers:
        - name: backend
          image: us-docker.pkg.dev/manage-robot/backend-repo/myapp-backend:TAG_VERSION
          ports:
            - containerPort: 8080