apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb      
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://admin:password123@mongodb-service:27017/manage-robot?authSource=admin"
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongodb-service"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "manage-robot"
            - name: SPRING_DATA_MONGODB_USERNAME
              value: "admin"
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: "password123"
