spring.application.name=backend
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://admin:password123@localhost:27017/robotdb?authSource=admin}
spring.data.mongodb.host=localhost
spring.data.mongodb.port=8080
spring.data.mongodb.database=Cluster0
logging.level.org.springframework.security=DEBUG


mqtt.broker= tcp://<IP_RASPBERRY_PI>:1883
mqtt.client-id= backend
mqtt.topic= robot/commands

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=robotnet14@gmail.com
spring.mail.password=robotnet14ROBOT
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true