spring.application.name=backend

# MongoDB Configuration - Utiliser le service Kubernetes
spring.data.mongodb.uri=mongodb://admin:password123@mongodb-service:27017/robotdb?authSource=admin

# NE PAS définir ces propriétés si vous utilisez spring.data.mongodb.uri
# spring.data.mongodb.host=mongodb-service
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=robotdb

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

# MQTT Configuration
mqtt.broker=tcp://<IP_RASPBERRY_PI>:1883
mqtt.client-id=backend
mqtt.topic=robot/commands

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=robotnet14@gmail.com
spring.mail.password=robotnet14ROBOT
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true